### ISSUE TITLE
Move extension popup under extension button

### ISSUE THREAD

**Issue by mubaidr** [joelspadin/SitePreferences#5]
Extension button is best place for extension popup reason being; If javaScript is disabled for current site and i want to enable it (or change other permissions), this extension won't be able to show any popup.

**Comment by joelspadin** [comment]
This is definitely a problem, but I'd like to avoid cluttering up the toolbar with an icon that only gets used occasionally. I think I can use a page action for this though, so an icon only appears when you are on a page for which you've disabled scripts.

**Comment by mubaidr** [comment]
User can easily hide icon from tool-bar (Extension page provide this functionality), so this is a win-win situation. :+1: .

(For example most of ad blockers only show count of blocked request. :-1: but the good thing is one can hide that icon from tool-bar)

And also showing icon for pages that only have JavaScript disabled might confuse many users.

**Comment by joelspadin** [comment]
You can hide the icon, but unless the popup can still appear when the icon is gone and I can programmatically trigger it (I have no idea if this is possible), this means you have to go back and re-enable the icon every time you disable scripts somewhere.

**Comment by joelspadin** [comment]
Okay. I see no way to programmatically open a popup, so it seems to me that the best solution would be to open the settings window in a new tab owned by the extension if scripts are disabled for the current site.

**Comment by mubaidr** [comment]
Why not keep the current functionality and add new icon with same function (all code will be reused). 
This means there will be two methods to access settings. 

Users like me who would prefer tool-bar icon can disable context menu option and vice versa.

**Comment by joelspadin** [comment]
I can add the toolbar icon too, but if the user has disabled scripts and tries to open it via the context menu, I need some way to make that still work.

**Comment by mubaidr** [comment]
~~One idea is to change change extension-icon to some notification icon to notify user when context menu is clicked when JS is disabled.
downside: this is only useful when extension icon is visible.~~

**Comment by mubaidr** [comment]
Why not temporarily enable JS for current site when context menu is clicked until user closes that pop-up or change JS setting for this site? :+1:

**Comment by joelspadin** [comment]
I believe it takes a page refresh for things to take effect, but I'm not sure about that. I'll have to check.

**Comment by mubaidr** [comment]
Pls try the `temp enable js` method before anything, because it seems efficient and quick fix.

> so it seems to me that the best solution would be to open the settings window in a new tab owned by the extension if scripts are disabled for the current site.

If above solution does not work, this should be most suitable implementation.

**Comment by joelspadin** [comment]
Yep. That will be the first thing I try, followed by opening in a new tab if that doesn't work. 

-----Original Message-----

**Comment by joelspadin** [comment]
Force JavaScript to enabled doesn't appear to work. As I suspected, it looks like it requires a page refresh before the changes take effect.

**Comment by mubaidr** [comment]
I just had thought, what if you you follow following procedure?

-User opens preferences, with disabled JS
-Enable JavaScript
-Insert iFrame into current document and load Extension options in it.(instead of directly injecting into original document)

**Comment by joelspadin** [comment]
Unfortunately, I can't insert an iframe into the document because scripting is disabled, and I can't enable scripting without refreshing the page. 

I just submitted an update with both a toolbar icon and a special case so that the context menu opens the preferences in a new tab if scripting is disabled. It's not ideal, but I don't think it's particularly confusing since it lists the site you are editing at the top. 

-----Original Message-----

**Comment by mubaidr** [comment]
Ohh.. yes you are right, what was i thinking. :laughing: 

Yes, the new implementation sounds right. Will test and report back when it will be published!

**Comment by mubaidr** [comment]
Now it works fine! :+1:
