### ISSUE TITLE
Can't control cookie deletion within Opera

### ISSUE THREAD

**Issue by reaseno** [joelspadin/SitePreferences#8]
When I say Opera should delete all cookies after closing it also deletes the cookies set to "Allow" with this addon, after Opera restart.

If I say Opera to keep all cookies, and set the sites which should only keep cookies for this session, then all cookies also those are kept after restart. So for me its currently not working :(

But thats probably an issue of Opera. I'm not sure.

I really need a working cookie management in which I can say, that all cookies should be deleted after restart and only some should be kept.

I'm also searching an delete all cookies of the current site button.

**Comment by joelspadin** [comment]
If you go to Opera's settings page ([opera:settings](opera://settings)), Privacy & security, and then Manage exceptions... under Cookies, do you see yellow Allow entries for the sites in question? They would have an info icon to the right, and clicking that should say "This setting is controlled by Site-specific Preferences".

If so, there's nothing I can do. I can only set the content policy (allow, save for the session only, or block), and it's up to Opera to decide what that means.

**Comment by reaseno** [comment]
Yes, the entries are there. Thats why I also thought its an Opera issue :/
But thank you very much for your answer ;)
